### ISSUE TITLE
Errors during installation on Windows

### ISSUE THREAD

**Issue by specblades** [rvion/CushyStudio#113]
All the errors i get

<img width="853" alt="image" src="https://github.com/rvion/CushyStudio/assets/113993746/1ae24452-97c4-46ad-8e85-19031cd273d0">

**Comment by ShashwatDubey99** [comment]
same here

**Comment by ShashwatDubey99** [comment]
but nothing problem fixed after wait

**Comment by rvion** [comment]
So, it resolve itself ?

**Comment by ShashwatDubey99** [comment]
> So, it resolve itself ?

Yeah but  don't know how and why

**Comment by rvion** [comment]
I really really want to fix those install issues. I tried to do something a bit original here: I bootstrap a portable js environment from nothing via a shell script

1. Download pnpm binary (portable, not too big, self contained)
2. Use pnpm to install electron and other dependencies 
3. Use electron as it if was node, and finish installing things
4. Use electron to run the release script locally to build the current version of cushy

This way, all users have both a full dev AND prod environment ready to hack around.


For now, I'm still thinking it's a cool approach worth pursuing, because cushy really shines when you have vscode around ready to open and because this helps bring contributors. But I'm no windows bat script expert. 🥲

For now, people have various success running the top-level scripts (install or update to get it working / start to run the prod version compiled by install or update / start-dev to run in dev-mode / clean to try to fix things and wipe various cache pnpm and electron folders)

**Comment by rvion** [comment]
Does update now correctly finishes ?

**Comment by ShashwatDubey99** [comment]
Can you guys tell me where comfyui related things are in your project (of api) I just want to change some things for myself

**Comment by rvion** [comment]
wanna drop on discrod (invite in the readme) and have a quick call right now ?

soon, Cushy will be able to install it's own sub ComfyUI setup.
for now, Cushy need to connect to any running ComfyUI install.

![image](https://github.com/rvion/CushyStudio/assets/2150990/5f947a12-e2a8-45bb-a464-f755118ad97a)

![image](https://github.com/rvion/CushyStudio/assets/2150990/54630da4-0528-467a-831f-3603e7faa26c)

once you configure a valid host, and set it as primary, you'll see `WS` and `Schema` in green,

![image](https://github.com/rvion/CushyStudio/assets/2150990/a36995cb-80ac-4429-a8b1-7d6821a68421)

and Cushy will generate a full blown type-safe sdk there: `schema/global.d.ts`

with stuff like that:

![image](https://github.com/rvion/CushyStudio/assets/2150990/3cbdd3fe-b417-4b4e-a9f5-a39d65ebc36f)

**Comment by rvion** [comment]
@specblades scripts have been changed a bit since I thitnk; does it work now ?
can you try to update ?

**Comment by ad-astra-video** [comment]
I had to install nodejs on system, close and open CMD window and install worked.  I think need to check for `node` in windows install and if not there download portable nodejs and update PATH in windows install script.

Got some warnings on supabase though, not sure if impacting installation yet.

` WARN  Failed to create bin at D:\AI\CushyStudio\node_modules\.bin\supabase. ENOENT: no such file or directory, stat 'D:\AI\CushyStudio\node_modules\supabase\bin\supabase.EXE'`

**Comment by rvion** [comment]
> I had to install nodejs on system

this is unfortunate; probably a few unfortunate consequence of recent package additions; probably a few missing `--ignore-scripts` here and there

> Got some warnings on supabase

some momrem binary-related warnings. supabase binary isn't even needed for users, only the lib. 🙃

I guess I'll setup a few VM this week, with various windows OS / config (with/without node) and try to refine  install scripts

**Comment by specblades** [comment]
> @specblades scripts have been changed a bit since I thitnk; does it work now ? can you try to update ?

Will try later, ty

**Comment by rvion** [comment]
the scripts have been rewritten.
local portable node is installed. only signed binaries, no more pnpm
everything "should" work now
