### ISSUE TITLE
Efficiency nodes optional pin not seen as optional in cushystudio

### ISSUE THREAD

**Issue by JustNeutral0** [rvion/CushyStudio#14]
the new update for efficiency nodes added a script pin to the ksampler efficient node and added a script node for the pin to make an x/y plot, when using the sampler node (efficient) it errors out and sees the script bit as required instead of optional

**Comment by rvion** [comment]
thanks ! 

should be fixed in v0.0.81

![image](https://user-images.githubusercontent.com/2150990/233742574-2413c1b5-01a3-4018-83ef-b81d1723b995.png)


be sure 
- to pull changes in your custom node subfolder (`git pull` in `efficiency-nodes-comfyui`)
- to restart ComfyUI backend so it properly send the updated schema

please re-open if it still doesn't work !

**Comment by JustNeutral0** [comment]
everything is up to date, comfyui restarted, i even went and deleted cushy.d.ts, nodes.d.ts, and nodes.json before restarting comfyui and then cushy/vscode and it still has the script problem

**Comment by rvion** [comment]
oh weird, let me PM you so we can debug this 👍

**Comment by rvion** [comment]
fixed in the new rewrite :)
